version: '3'
services:
  backend:
    container_name: "bedes_backend_compose_container"
    env_file:
      - "environment/backend.env"
      - "environment/postgres.env"
    build:
      context: "."
      dockerfile: "./build/Dockerfiles/Dockerfile-backend"
    ports:
      - "3009:3000"
    depends_on:
      - "db"
  frontend:
    container_name: "bedes_nginx_compose_container"
    build:
      context: "./"
      dockerfile: "./build/Dockerfiles/Dockerfile-nginx-local"
    ports:
      - 8086:80
    depends_on:
      - "backend"
  scripts:
    container_name: "bedes_scripts_compose_container"
    env_file:
      - "environment/backend.env"
      - "environment/postgres.env"
    build:
      context: "."
      dockerfile: "./build/Dockerfiles/Dockerfile-scripts"
    depends_on:
      - "db"
  db:
    image: postgres:11.0
    container_name: "bedes_db_compose_container"
    build:
      context: "."
    env_file:
      - "./environment/backend.env"
      - "./environment/postgres.env"
    expose:
      - 5432
    ports:
      - "5461:5432"
    volumes:
      - ./scripts/db:/create-epb-db
      - ./bedes-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./bedes-db/postgres_data:/var/lib/postgresql/data/pgdata
