FROM node:10.16.3-alpine

USER root

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm config set unsafe-perm true
RUN npm install -g @angular/cli@^7.0.4

COPY --chown=node:node bedes-frontend /app/bedes-frontend
COPY --chown=node:node bedes-common /app/bedes-common

RUN cd /app/bedes-common && npm install && cd /app/bedes-frontend && npm install
WORKDIR /app/bedes-frontend
RUN npm run build
CMD node /app/server.js"
